services:
  postgresql:
    image: postgres:11.7
    container_name: ps-psql-tracker
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=time_track_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  ps: